
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 13 17:51:26 EST 2022
//----------------------------------------------------

package MPC;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCTION = 14;
  public static final int CONST = 7;
  public static final int GE = 45;
  public static final int OVERRIDES = 23;
  public static final int METHODS = 16;
  public static final int CASE = 6;
  public static final int SEMI = 39;
  public static final int LPAREN = 34;
  public static final int REPEAT = 27;
  public static final int INT = 54;
  public static final int ARRAY = 4;
  public static final int MINUS = 49;
  public static final int FOR = 13;
  public static final int RPAREN = 35;
  public static final int NOT = 19;
  public static final int AND = 3;
  public static final int LT = 40;
  public static final int RECORD = 26;
  public static final int TYPE = 30;
  public static final int NIL = 18;
  public static final int OBJECT = 20;
  public static final int OR = 22;
  public static final int COMMA = 36;
  public static final int DOTDOT = 53;
  public static final int DIV = 8;
  public static final int BEGIN = 5;
  public static final int UNTIL = 31;
  public static final int PLUS = 48;
  public static final int ASSIGN = 46;
  public static final int IF = 15;
  public static final int CARET = 52;
  public static final int ID = 56;
  public static final int DOT = 37;
  public static final int LE = 43;
  public static final int OF = 21;
  public static final int ABSTRACT = 2;
  public static final int EOF = 0;
  public static final int AST = 47;
  public static final int error = 1;
  public static final int PROGRAM = 25;
  public static final int MOD = 17;
  public static final int EQ = 41;
  public static final int LBRACK = 50;
  public static final int COLON = 38;
  public static final int ELSE = 11;
  public static final int RBRACK = 51;
  public static final int TO = 29;
  public static final int WHILE = 33;
  public static final int THEN = 28;
  public static final int NE = 44;
  public static final int END = 12;
  public static final int STRING = 55;
  public static final int DOWNTO = 10;
  public static final int GT = 42;
  public static final int VAR = 32;
  public static final int PROCEDURE = 24;
  public static final int DO = 9;
}

